### ISSUE TITLE
Doesn't work on android 

### ISSUE THREAD

**Issue by The96rf** [youngerelk1/RSDK-GDT#3]
I tried to play on android but it didn't work, I did the steps and it still didn't work pls help

**Comment by youngerelk1** [comment]
you have to use https://github.com/Sonic-Geared/Scarlet-Engine. because V4 on android has a bug that makes it want to load the HW menus (GDT doenst have them)

**Comment by The96rf** [comment]
Ok but there is a problem, I don't know how to build

**Comment by SketchyGear** [comment]
> Ok but there is a problem, I don't know how to build

just use the autobuilds at the Actions section of the repo and you should be good

**Comment by Soniden** [comment]
Hey(alt account cause I fogor💀 password)
I looked everywhere for the autobuild, still can't find it, link?

**Comment by SketchyGear** [comment]
https://github.com/Sonic-Geared/Scarlet-Engine/actions
try looking at this section, it has all the autobuilds/workflows that were made atm

**Comment by Soniden** [comment]
I always check it but there aren't downloads just how to build it
